service: awsip-notifier

frameworkVersion: '3'

package:
  patterns:
    - '!resources/**'
    - '!node_modules/**'
    - '!*.json'
    - '!config/**'

plugins:
  - serverless-plugin-log-retention
  - serverless-iam-roles-per-function
custom:
  env: ${file(config/${opt:stage, 'dev'}.yaml)}
  logRetentionInDays: 30


provider:
  name: aws
  runtime: python3.11
  region: eu-west-1
  stage: dev

functions:
  - ${file(resources/ipcatcher/function.yaml)}


resources:
  - ${file(resources/ipcatcher/functionRole.yaml)}
  - ${file(resources/common/ebRule.yaml)}
  - ${file(resources/common/sqs.yaml)}